# Generated by Django 3.2.25 on 2025-08-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('company', 'Company')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('equivalents', models.ManyToManyField(blank=True, related_name='_organization_organizationunit_equivalents_+', to='organization.OrganizationUnit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
