# Generated by Django 4.2.16 on 2025-06-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('department_level1', 'Department Level 1'), ('department_level2', 'Department Level 2'), ('department_level3', 'Department Level 3'), ('department_level4', 'Department Level 4'), ('department_level5', 'Department Level 5')], max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationunit')),
            ],
        ),
    ]
