import os
import sys
import django

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vnw.settings')
django.setup()
from people.resume_parser import parse_resume_text

# Example resume 1
text1 = """TÓM TẮT TIỂU SỬ\nĐỒNG CHÍ PHẠM THỊ  THANH TRÀ\nỦy viên Trung  ương Đảng, Phó Trưởng Ban Tổ chức Trung ương,\nBộ trưởng Bộ Nội vụ\n- Ngày sinh:  21/01/1964   Nam/Nữ: Nữ      Dân tộc: Kinh\n- Quê quán: Xã Nam  Yên, huyện Nam Đàn, tỉnh Nghệ An\n- Thành phần gia đình:  Công chức\n- Nghề nghiệp khi được  tuyển dụng: Giáo viên\n- Ngày được tuyển dụng làm cán  bộ, công chức, viên chức: 15/8/1985\n- Ngày vào Đảng:  12/6/1993    Ngày chính thức: 12/6/1994\n- Trình độ được đào  tạo:\n+ Giáo dục phổ thông:  10/10\n+ Chuyên môn nghiệp  vụ: Cử nhân sư phạm Ngữ văn\n+ Học hàm, học vị:  Thạc sĩ Quản lý Giáo dục\n+ Lý luận chính trị:  Cao cấp\n- Khen thưởng: Huân  chương Lao động hạng Nhì\n- Ủy viên Ban Chấp  hành Trung ương Đảng khóa XII, XIII\n- Đại biểu Quốc hội\nkhóa  XV\n- Bộ trưởng Bộ Nội  vụ\nTÓM TẮT QUÁ TRÌNH  CÔNG TÁC\n9/1985 - 8/1987:\nGiáo  \t\tviên Trường Trung tâm thực hành huyện Trấn Yên, tỉnh Yên Bái.\n9/1987 - 10/1997:\nCán  \t\tbộ chỉ đạo chuyên môn Phòng Giáo dục và Đào tạo huyện Trấn Yên, tỉnh Yên  \t\tBái.\n11/1997 - 11/1999:\nPhó  \t\tTrưởng phòng Giáo dục và Đào tạo huyện Trấn Yên, tỉnh Yên Bái.\n12/1999 - 11/2000:\nUỷ  \t\tviên Ban Chấp hành Đảng bộ huyện, Phó Chủ tịch Ủy ban nhân dân huyện  \t\tTrấn Yên, tỉnh Yên Bái.\n12/2000 - 01/2002:\nỦy  \t\tviên Ban Chấp hành Đảng bộ tỉnh, Ủy viên Ban Chấp hành Trung ương Đoàn,  \t\tPhó Bí thư Tỉnh đoàn Yên Bái.\n02/2002 - 01/2006:\nỦy  \t\tviên Ban Chấp hành Đảng bộ tỉnh rồi Ủy viên Ban Thường vụ Tỉnh ủy (từ  \t\ttháng 10/2005), Ủy viên Ban Thường vụ Trung ương Đoàn, Bí thư Tỉnh Đoàn  \t\tYên Bái.\n02/2006 - 3/2008:\nỦy viên Ban Thường vụ  \t\tTỉnh ủy, Trưởng Ban Tuyên giáo Tỉnh ủy Yên Bái.\n4/2008 - 4/2011:\nỦy viên Ban Thường vụ  \t\tTỉnh ủy, Phó Chủ tịch Ủy ban nhân dân tỉnh Yên Bái.\n4/2011 - 5/2014:\nỦy viên Ban Thường vụ  \t\tTỉnh ủy, Bí thư Thành ủy Yên Bái, tỉnh Yên Bái.\n5/2014 - 9/2016\n- Phó Bí thư Tỉnh ủy rồi  \t\tBí thư Ban Cán sự đảng Ủy ban nhân dân, Chủ tịch Uỷ ban nhân dân tỉnh  \t\tYên Bái.\n- Ủy viên Ban Chấp hành  \t\tTrung ương Đảng khóa XII (tháng 01/2016)\n10/2016 - 01/2017:\nUỷ viên Ban Chấp hành  \t\tTrung ương Đảng, Bí thư Tỉnh ủy, Chủ tịch Uỷ ban nhân dân tỉnh, Bí thư  \t\tĐảng uỷ quân sự tỉnh Yên Bái.\n02/2017 - 9/2020:\nUỷ viên Ban Chấp hành  \t\tTrung ương Đảng, Bí thư Tỉnh ủy, Chủ tịch Hội đồng nhân dân tỉnh, Bí thư  \t\tĐảng uỷ quân sự tỉnh Yên Bái.\n10/2020\n- 3/2021:\nỦy viên Ban Chấp  \t\t\thành Trung ương Đảng, Phó Trưởng Ban Tổ chức Trung ương, Ủy viên Ban  \t\t\tcán sự\nđảng, Thứ trưởng Bộ Nội\n4/2021:\n-\nỦy viên Ban Chấp hành Trung ương Đảng, Phó Trưởng Ban Tổ  \t\tchức Trung ương, Bí thư Ban cán sự đảng Bộ Nội vụ.\n4/2021 - nay:\nỦy viên Ban Chấp hành Trung ương Đảng, Bí thư Ban cán sự đảng, Bộ trưởng Bộ Nội vụ.\n24/01/2025:\nBộ Chính trị chỉ định tham gia Ban Chấp hành, Ban Thường vụ Đảng ủy Chính phủ nhiệm kỳ 2020 – 2025.
"""

# Example resume 2
text2 = """Tóm tắt tiểu sử Thống đốc Ngân hàng Nhà nước Việt Nam\nLê Minh Hưng\nThống đốc Ngân hàng Nhà nước Lê Minh Hưng\n- Ngày sinh: 11/12/1970\n- Quê quán: xã Sơn Tân, huyện Hương Sơn, tỉnh Hà Tĩnh\n- Ngày vào Đảng: 21/8/2000         Ngày chính thức: 21/8/2001\n- Học hàm học vị: Thạc sỹ Chính sách công\n- Lý luận chính trị: Cao cấp\n- Ủy viên Trung ương Đảng khóa XII\nTÓM TẮT QUÁ TRÌNH CÔNG TÁC\n10/1993 - 1/1998: Chuyên viên Phòng Quỹ Tiền tệ Quốc tế, Vụ Quan hệ Quốc tế, Ngân hàng Nhà nước Việt Nam. Tham dự khóa học về kinh tế thị trường và phân tích tài chính của Quỹ Tiền tệ Quốc tế (IMF) tại Trường Đại học Kinh tế Tài chính Thượng Hải, Trung Quốc (tháng 3-6/1996); Học Thạc sỹ về kinh tế tại trường Đại học Tổng hợp Saitama, Nhật Bản (tháng 10/1996 - 9/1997).\n2/1998 - 2/2002: Phó phòng rồi Trưởng phòng Ngân hàng Phát triển Châu Á.\n3/2002 - 12/2009: Phó Vụ trưởng rồi Vụ trưởng Vụ Hợp tác Quốc tế, Ngân hàng Nhà nước Việt Nam.\n01/2010 - 10/2011: Ủy viên Ban Cán sự Đảng, Vụ trưởng Vụ Tổ chức cán bộ, Ngân hàng Nhà nước Việt Nam.\n10/2011 - 10/2014: Ủy viên Ban Cán sự Đảng, Phó Thống đốc Ngân hàng Nhà nước Việt Nam.\n11/2014 - 01/2016: Phó Chánh Văn phòng Trung ương Đảng. Tại Đại hội đại biểu toàn quốc lần thứ XII của Đảng được bầu vào Ban Chấp hành Trung ương Đảng.\n01/2016 – 4/2016: Ủy viên Trung ương Đảng, Phó Chánh Văn phòng Trung ương Đảng.\n4/2016 - 12/11/2020: Ủy viên Trung ương Đảng, Thống đốc Ngân hàng Nhà nước Việt Nam./.
"""

for i, text in enumerate([text1, text2], start=1):
    print(f"\n--- Parsed Result for Resume {i} ---")
    parsed = parse_resume_text(text)
    for key, value in parsed.items():
        print(f"{key}: {value}")
