# Generated by Django 3.2.25 on 2025-08-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('company', 'Company')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('equivalents', models.ManyToManyField(blank=True, related_name='_organizations_organization_equivalents_+', to='organizations.Organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': 'Organization Units',
            },
        ),
    ]
