# Generated by Django 3.2.25 on 2025-08-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('name_en', models.CharField(blank=True, max_length=225, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('central', 'Central'), ('provincial', 'Provincial'), ('district', 'District'), ('commune', 'Commune')], max_length=50, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('equivalents', models.ManyToManyField(blank=True, related_name='_organizations_organization_equivalents_+', to='organizations.Organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organizationtype')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
