# Generated by Django 3.2.25 on 2025-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
