# Generated by Django 3.2.25 on 2025-09-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='normalized_name_ascii',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
