# Generated by Django 3.2.25 on 2025-09-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_normalized_name_ascii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='normalized_name_ascii',
            new_name='name_ascii',
        ),
    ]
