# Generated by Django 3.2.25 on 2025-09-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_notes'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('law_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_passed', models.DateField(blank=True, null=True)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.legislation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation.legislation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='legislation',
            name='organizations_involved',
            field=models.ManyToManyField(through='legislation.OrganizationLegislation', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='legislation',
            name='people_involved',
            field=models.ManyToManyField(through='legislation.PersonLegislation', to='people.Person'),
        ),
    ]
