# Generated by Django 3.2.25 on 2025-08-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hometown', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_death', models.CharField(blank=True, max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('date_entered_party', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entered_party_official', models.CharField(blank=True, max_length=20, null=True)),
                ('expertise', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('political_theory', models.CharField(blank=True, max_length=100, null=True)),
                ('foreign_language', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('position_process', models.TextField(blank=True, null=True)),
                ('cabinets', models.ManyToManyField(blank=True, related_name='members', to='people.Cabinet')),
            ],
            options={
                'unique_together': {('name', 'hometown', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('start', models.CharField(blank=True, max_length=20, null=True)),
                ('end', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='people.person')),
            ],
        ),
    ]
