# Generated by Django 4.2.16 on 2024-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('date_of_death', models.IntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('date_entered_party', models.DateField(blank=True, null=True)),
                ('date_entered_party_official', models.DateField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_education', models.CharField(blank=True, max_length=100, null=True)),
                ('political_theory', models.CharField(blank=True, max_length=100, null=True)),
                ('foreign_language', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=1000, null=True)),
                ('position_process', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
