# Generated by Django 3.2.25 on 2025-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Cabinet', 'verbose_name_plural': 'Cabinets'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personposition',
            options={'verbose_name': 'Person Position', 'verbose_name_plural': 'Person Positions'},
        ),
    ]
