# Generated by Django 3.2.25 on 2025-09-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('sibling', 'Sibling')], max_length=20)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='people.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='people.person')),
            ],
            options={
                'verbose_name': 'Person Relationship',
                'verbose_name_plural': 'Person Relationships',
                'unique_together': {('from_person', 'to_person', 'relationship_type')},
            },
        ),
    ]
