# Generated by Django 3.2.25 on 2025-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
